# This file contains a series of unit tests that compare expected and actual javascript code generated by pyd3xter
# instructions:
# install pytest: http://pytest.org/latest/
# $> python -m pytest -v unit.py
# TODO: refactor to streamline js comparisons; consider edge cases, syntactic curbballs
# note: expected_js field hand-written

# BUG: inproper spacing

from PyDexter import PyDexter

def strip_space(str):
	return ''.join(str.split())

def test_hist():
	''' indirectly compares actual to expected js generated by PyDexter hist method '''
	test_input = [1,2,3,4,5]
	chart_type = 'hist'
	expected_js = strip_space("new D3xter({}).hist([1, 2, 3, 4, 5]); \n")
	actual_js = strip_space(PyDexter()._make_js(chart_type,test_input))
	assert actual_js == expected_js
	
def test_scatter_with_snd_arg():
	chart_type = 'plot'
	test_input_x1 = [0,1]
	test_input_x2 = [0,1]
	test_config = {'datasets': [{'y': [0, 1], 'x': [0, 1]}]}
	actual_js = PyDexter()._make_js(chart_type,test_config)
	expected_js = "new D3xter({}).plot({'datasets': [{'y': [0, 1], 'x': [0, 1]}]}); \n"
	assert actual_js == expected_js

def test_scatter_without_snd_arg():
	chart_type = 'plot'
	test_input_x1 = [0,1]
	test_input_x2 = None
	test_config = {'datasets': [{'y': [0, 1], 'x': [0 ,1]}]}
	actual_js = PyDexter()._make_js(chart_type,test_config)
	expected_js = "new D3xter({}).plot({'datasets': [{'y': [0, 1], 'x': [0, 1]}]}); \n"
	assert actual_js == expected_js

def test_plot():
	''' compares actual to expected js generated by PyDexter plot method '''
	test_input = [1,2,3,4,5]
	chart_type = 'plot'
	expected_js = "new D3xter({}).plot([1, 2, 3, 4, 5]); \n"
	actual_js = PyDexter()._make_js(chart_type,test_input)
	assert actual_js == expected_js

def test_pie():
	''' compares actual to expected js generated by PyDexter pie method '''
	test_input = [1,2,3,4,5]
	chart_type = 'pie'
	expected_js = "new D3xter({}).pie([1, 2, 3, 4, 5]); \n"
	actual_js = PyDexter()._make_js(chart_type,test_input)
	assert actual_js == expected_js

def test_timeline():
	''' compares actual to expected js generated by PyDexter timeline method '''
	test_input = [1,2,3,4,5]
	chart_type = 'timeline'
	expected_js = "new D3xter({}).timeline([1, 2, 3, 4, 5]); \n"
	actual_js = PyDexter()._make_js(chart_type,test_input)
	assert actual_js == expected_js

def test_bar():
	''' compares actual to expected js generated by PyDexter bar method '''
	test_input = [1,2,3,4,5]
	chart_type = 'bar'
	expected_js = "new D3xter({}).bar([1, 2, 3, 4, 5]); \n"
	actual_js = PyDexter()._make_js(chart_type,test_input)
	assert actual_js == expected_js
